#-*- coding: utf-8 -*-
from django.utils.translation import ugettext as _

SUBMISSION_STATUS_PROPOSED = 0
SUBMISSION_STATUS_EVAL     = 1
SUBMISSION_STATUS_ACCEPTED = 2
SUBMISSION_STATUS_OBSERVED = 3
SUBMISSION_STATUS_REJECTED = 4

SUBMISSION_STATUS_CHOICES = (
    (SUBMISSION_STATUS_PROPOSED, _(u'Proposed')),
    (SUBMISSION_STATUS_EVAL,     _(u'In evaluation')),
    (SUBMISSION_STATUS_ACCEPTED, _(u'Accepted')),
    (SUBMISSION_STATUS_OBSERVED, _(u'Observed')),
    (SUBMISSION_STATUS_REJECTED, _(u'Rejected')),
)
